tasks:
    - name: backend
      before: |
        pip install --upgrade pip
        pip install -r requirements.txt
        rustup default nightly
        cargo install flamegraph
        sudo apt update -y
        sudo apt install linux-tools-common linux-tools-generic -y
        python prepro_tinyshakespeare.py
        python train_gpt2.py
        make
        make train
